<!DOCTYPE html>
<html>
<head>
  	<meta charset="utf-8">
	<title>Devious Ideas</title>
	<link rel='stylesheet' href='fonts/brand/brandicon.css'>
	<script src='js/jquery.min.js'></script>
	<script type="text/javascript">
	    $(document).ready(function() { 
		    
		    //on load hide the lists
		    $('.list').slideToggle(200);
		    // on click toggle lists
		    $('.folder .folderTitle').on('click', function(e) {
			   e.preventDefault();
			   //e.stopPropagation();
			   
			   var link = $(this);
			   
			   $(this).next('.list').slideToggle(200);
			    
		    });
		    
		    
		    
		    });
    </script>
</head>
<body>
	
	
	<style>
		@font-face {
		  font-family: 'Calibre-Thin';
		  src: url(fonts/calibre/Calibre-Thin.otf);
		  font-weight: normal;
		  font-style: normal; }
		@font-face {
		  font-family: 'Calibre-Light';
		  src: url(fonts/calibre/Calibre-Light.otf);
		  font-weight: normal;
		  font-style: normal; }
		@font-face {
		  font-family: 'Calibre-Regular';
		  src: url(fonts/calibre/Calibre-Regular.otf);
		  font-weight: normal;
		  font-style: normal; }
		@font-face {
		  font-family: "Calibre-Semibold";
		  src: url(fonts/calibre/Calibre-Semibold.otf) format("opentype");
		  font-weight: normal;
		  font-style: normal; }
		@font-face {
		  font-family: "Calibre-Bold";
		  src: url(fonts/calibre/Calibre-Bold.otf) format("opentype");
		  font-weight: normal;
		  font-style: normal; }
  
		* {
			box-sizing: border-box;
		}
		
		body { 
			font-family: 'Calibre-Regular';
			font-size: 13px;
			color: #666;
			background: #f2f2f2;
			padding: 50px 25px;
			min-width: 640px;
		}
		
		section {
			width: 100%;
			max-width: 720px;
			min-width: 640px;
			margin: 0 auto;
			display: block;
		}
		
		h1, h2, h3, h4 {
			font-size: 15px;
			margin: 0;
			padding: 0 0 0 0px;
		    line-height: 16px;
			display: inline-block;
			font-family: 'Calibre-Regular';
			font-weight: normal;
		}
		
		h1.title {
			font-size: 24px;
			margin-bottom: 20px;
			padding: 0 0 0 0;
			display: block;
			font-family: 'Calibre-Semibold';
			font-weight: normal;
		}
		.folderTitle {
			cursor: pointer;
		}
		div h1 {
			font-size: 17px;
			font-family: 'Calibre-Semibold';
		}
		div h2 {
			font-size: 15px;
		}
		div h3 {
			font-size: 15px;
		}
		
		
		
		.folder {
			padding: 10px 0 0 25px;
			
			 position: relative;
		}
		
		.folder:before {
		  content: "\e614";
		  display: inline-block;
		  line-height: inherit;
		  font-size: 15px;
		  font-family: "DA-brandicons";
		  vertical-align: top;
		  color: rgba(0,0,0,.2);
		  position: absolute;
		  left: 0;
		}
		
		[data-folder="1"] {
			margin-bottom: 15px;
			padding: 10px 0 0 20px;
		}
		
		[data-folder="1"]:before {
			content: "\e61f" !important;
			font-size: 17px !important;
		}
		
		
		
				
		.list {
			padding: 5px 0px 5px 0px;
			margin-bottom: 10px;
		}
		.list span.date {
			    float: right;
			    color: rgba(0,0,0,.35);	
			    font-size: 12px;	
			    line-height: 16px;
				display: inline-block;	
		}
		
		.list a {
			font-size: 14px;
			color: #666;
			text-decoration: none;
			    display: inline-block;
		}
		.list a:hover {
			color: black;
			text-decoration: underline;
		}
		
		
		.item {
			padding: 7px 0 7px 0;
			border-bottom: 1px solid rgba(0,0,0,.1);
		}
		.item:hover {
			background: rgba(255,255,255,0.5);
		}
		.item:first-of-type {
			margin-top: 5px;
			border-top: 1px solid rgba(0,0,0,.1);
		}
		
		
		
		
		
		
	</style>
	
	<section>
	
	<h1 class="title">DeviantArt Demos, Prototypes and other interesting stuff</h1>
		
		
		
	
	<?PHP
	// NOTES
		// code generated by HSFR & IFR june 2017. You're welcome.
	
	// TO DO
		// default list by newest
		// need to add case where an empty folder is encountered
		// add time stamp of most recent modification to folder	

	  function getFileList( $dir, $depth )
	  {
	    $dirListing = scandir( $dir );
	
		if ( isHTMLFilePresent( $dir ) ) {
			// HTML file in this folder so scan this folder for HTML files and exit
			echo "<div class=\"list\" data-level=\"{$depth}\">";
	       	foreach ( $dirListing as $key => $value ) {
		       	// If file name ends with html then output file name
		        if ( !preg_match("/^\./", $value ) ) {
					$fullName = "$dir/$value";
				    if ( preg_match("/\.html$/", $value ) ) {
		 		      // echo file name
		 		      $lastModified = date( "F d Y, H:i", filemtime( $fullName ) );
		 			  echo "<div class=\"item\"><a href=\"{$fullName}\" target=\"_blank\">{$value}</a> <span class=\"date\">{$lastModified}</span> </div>\n";
		 			}
	 			}
			}
			echo "</div>";
			return;
		} else {
			// No html files so scan this folder and recurse to next level if folder found
			
			foreach ( $dirListing as $key => $value ) {
				
		        if ( !preg_match("/^\./", $value ) ) {
			        $fullName = "$dir/$value";
			        echo "<div class=\"folder\" data-folder=\"{$depth}\">";
					if ( is_dir( $fullName ) ) {
						// output a new heading at this level
						
						echo "<h{$depth} class=\"folderTitle\">{$value}</h{$depth}>\n";
						
						// Recurse into this folder
						getFileList( $fullName, $depth + 1 );
						
						
					}
					echo "</div>";	
				}
			}
			
		}
	  }




	function isHTMLFilePresent( $inFolder )
	{
       $fileListing = scandir( $inFolder );
       foreach ( $fileListing as $key => $value ) {
	      if( preg_match("/\.html$/", $value ) ) {
 		   return true;
		  }
		}
	    return false;
 	}
	 	
	 	
	 	
	 	
	?>	
	
	<?PHP
	  // list files in the current directory
	  
	  getFileList( "projects/", 1 );
	  
	?>
	
	</section>
	
	
	
	
</body>
</html>